from __future__ import annotations
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
ASSETS_DIR = BASE_DIR / "assets"
SCORES_FILE = DATA_DIR / "scores.json"
LEADERBOARD_PDF_FILE = DATA_DIR / "fruit_fury_leaderboard.pdf"
HAND_LANDMARKER_MODEL = ASSETS_DIR / "hand_landmarker.task"

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
SHOW_CAMERA_PREVIEW = True
CAMERA_PREVIEW_ALPHA = 95
USE_HAND_TRACKING = True

GRAVITY = 980.0
FRUIT_SPAWN_INTERVAL = 0.92
BOMB_PROBABILITY = 0.12
SPECIAL_PROBABILITY = 0.12
STARTING_LIVES = 3

MAX_TRAIL_POINTS = 14
TRAIL_POINT_LIFETIME = 0.24
MIN_SLICE_SPEED = 760.0
BLADE_RADIUS = 22

BASE_FRUIT_SCORE = 10
GOLDEN_FRUIT_SCORE = 60
COMBO_TIMEOUT = 1.2
SCORE_FLOAT_LIFETIME = 0.9

DIFFICULTY_PER_SCORE = 0.0009
DIFFICULTY_PER_SECOND = 0.012
MAX_DIFFICULTY = 2.7

FREEZE_DURATION = 4.0
FREEZE_FACTOR = 0.45
SHIELD_DURATION = 12.0

SOUND_VOLUME = 0.45
MUSIC_VOLUME = 0.22

LEADERBOARD_LIMIT = 100
